//
//  webapp_navbar.h
//  iOSHierarchyViewer
//
//
// THIS FILE IS GENERATED AUTOMATICALLY BY XCODE's script
//
//

#ifndef iOSHierarchyViewer_webapp_navbar 
#define iOSHierarchyViewer_webapp_navbar 

#define WEBAPP_NAVBAR @"ZnVuY3Rpb24gTmF2YmFyKG9wdGlvbnMpIHsKICAKICB2YXIgbyA9IG9wdGlvbnM7CiAgCiAgdmFyIGRvbSA9ICQoJzxkaXYgY2xhc3M9Im5hdmJhciI+PC9kaXY+Jyk7CiAgdmFyIHRpdGxlICA9ICQoJzxkaXYgY2xhc3M9Im5hdmJhcl90aXRsZSI+aU9TIEhpZXJhcmNoeSBWaWV3ZXI8L2Rpdj4nKTsKICB2YXIgbG9hZGluZyA9ICQoJzxkaXYgY2xhc3M9Im5hdmJhcl9sb2FkaW5nIj5Mb2FkaW5nLi4uLjwvZGl2PicpOwogIAogIGRvbS5hcHBlbmQodGl0bGUpOwogIGRvbS5hcHBlbmQobG9hZGluZyk7CiAgby5wYXJlbnREb20uYXBwZW5kKGRvbSk7CiAgCiAgdmFyIHNob3dMb2FkaW5nRnVuYyA9IGZ1bmN0aW9uKCkgeyBsb2FkaW5nLnNob3coKTsgfQogIHZhciBoaWRlTG9hZGluZ0Z1bmMgPSBmdW5jdGlvbigpIHsgbG9hZGluZy5oaWRlKCk7IH0KICAKICB2YXIgdmVyc2lvbkZ1bmMgPSBmdW5jdGlvbih2ZXIpIHsKICAgIHRpdGxlLnRleHQoJ2lPUyBIaWVyYXJjaHkgVmlld2VyICgnICsgdmVyICsgJyknKTsKICB9OwogIAogIGhpZGVMb2FkaW5nRnVuYygpOwogIAogIHJldHVybiB7CiAgICBkb21FbGVtZW50OiBkb20sCiAgICB2ZXJzaW9uOiB2ZXJzaW9uRnVuYywKICAgIHNob3dMb2FkaW5nOiBzaG93TG9hZGluZ0Z1bmMsCiAgICBoaWRlTG9hZGluZzogaGlkZUxvYWRpbmdGdW5jCiAgfTsKfQo="

#endif
